server.address=0.0.0.0
spring.main.lazy-initialization=true
spring.data.jpa.repositories.bootstrap-mode=deferred
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
app.bootstrap.seed.enabled=false
app.database.maintenance.enabled=false
